flashcards/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from . import views

app_name = "flashcards"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:flashcard_id>/", views.detail, name="detail")
]

highlights/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from . import views

app_name = "highlights"
urlpatterns = [
    # path("", views.index, name="index"),
    path("upload/", views.upload_file, name="upload_file"),
    path("process-upload/", views.handle_uploaded_file, name="process_upload"),
]

language_app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from language_app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("", include("django.contrib.auth.urls")),
    path("flashcards/", include("flashcards.urls")),
    path("highlights/", include("highlights.urls")),
    path("signup/", views.create_account, name="create_account"),
]

flashcards/models.py
from django.db import models

class Flashcard(models.Model):
    def __str__(self):
        return "\"" + self.front + "\"/\"" + self.back +  "\""

    front = models.CharField(max_length=240)
    back = models.CharField(max_length=240)


class Review(models.Model):
    def __str__(self):
        return str(self.difficulty) + " - " + str(self.review_due) + " - " + str(self.flashcard)
    
    last_review = models.DateField()
    review_due = models.DateField()
    difficulty = models.IntegerField()
    flashcard = models.ForeignKey(Flashcard, on_delete=models.CASCADE)

highlights/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User

class Highlight(models.Model):
    def __str__(self):
        return self.text

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    text = models.CharField(max_length=240)
    # book_id = models.TextField()
    # book_alias = models.TextField()

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class HighlightsSqlite(models.Model):
    document = models.FileField(upload_to=user_directory_path)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

highlights/forms.py
from django import forms
from .models import HighlightsSqlite
from django.contrib.auth.models import User

class UploadFileForm(forms.Form):
    title = forms.CharField(label="Title", max_length=50)
    file = forms.FileField()



class HighlightsSqliteForm(forms.ModelForm):
    class Meta:
        model = HighlightsSqlite
        # fields = ('document','user',)
        fields = ('document',)

flashcards/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Flashcard

@login_required
def index(request):
    """ flashcards = Flashcard.objects.all()
    template = loader.get_template("flashcards/index.html")
    context = {
        "flashcards": flashcards
    }
    return HttpResponse(template.render(context, request)) """

    flashcards = Flashcard.objects.all()
    context = {"flashcards": flashcards}
    return render(request, "flashcards/index.html", context)


def detail(request, flashcard_id):
    flashcard = get_object_or_404(Flashcard, pk=flashcard_id)
    return render(request, "flashcards/detail.html", {"flashcard": flashcard})

def add(request):
    try:
        front = request.POST["front"]
        back = request.POST["back"]
    except (KeyError):
        return render(
            request,
            "flashcards/index.html",
            {
                "error_message": "You need to provide a front and back for the flashcard",
            },
        )
    except:
        return render(
            request,
            "flashcards/index.html",
            {
                "error_message": "An error occurred",
            },
        )
    else:
        f = Flashcard(front=front, back=back)
        f.save()
        HttpResponseRedirect(reverse("flashcards:detail", args=(f.id,)))

highlights/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .forms import UploadFileForm, HighlightsSqliteForm

# from .file_processor import handle_uploaded_file
@login_required
def upload_file(request):
    if request.method == "POST":
        form = HighlightsSqliteForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return HttpResponseRedirect("/flashcards/")
    else:
        form = HighlightsSqliteForm()
    return render(request, "highlights/upload.html", {"form": form})

def handle_uploaded_file(f):
    with open("blob", "wb+") as destination:
        for chunk in f.chunks():
            destination.write(chunk)

language_app/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django import forms
from django.contrib.auth.forms import UserCreationForm  
from django.http import HttpResponseRedirect
from django.contrib import messages

def home(request):
    return render(request, "index.html")

def create_account(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account created successfully')  
            return HttpResponseRedirect("/")
    else:
        form = UserCreationForm()
    return render(request, "create_account.html", {"form": form})

flashcards/templates/flashcards/detail.html
<ul>
    <li>{{ flashcard.front}}
    <li>
    <li>{{ flashcard.back}}
    <li>
</ul>

flashcards/templates/flashcards/index.html
{% extends "master.html" %}

{% block title %}
Flashcards
{% endblock %}

{% block content %}

{% if flashcards %}
{% for fcard in flashcards %}
<div class="flashcard">
    <a href="{% url 'flashcards:detail' fcard.id %}">{{ fcard.front }}</a>
</div>
{% endfor %}

{% else %}
<p>No flashcards are available.</p>
{% endif %}
{% endblock %}

highlights/templates/highlights/process_upload.html
{% extends "master.html" %}

{% block title %}
Upload Kobo DB
{% endblock %}

{% block content %}
<form action="{% url 'highlights:process_upload' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

highlights/templates/highlights/upload.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- <label for="title">Title: </label> -->
    <!-- <input id="title" type="text" name="title" value="{{ title }}"> -->
    <!-- <input type="file" id="file" name="filename"> -->
    <!-- <input type="submit" value="OK"> -->
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>

templates/create_account.html
{% extends "master.html" %}

{% block title %}
Sign Up
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

templates/header.html
<header class="d-flex flex-wrap justify-content-center p-3 mb-4 border-bottom">
    <a href="/"
        class="fw-bold d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <svg class="bi me-2" width="40" height="32">
            <use xlink:href="#bootstrap"></use>
        </svg>
        <span style="color: #013f01;" class="fs-4">Eddie's App</span>
    </a>
    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'highlights:upload_file' %}">Upload</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'flashcards:index' %}">Cards</a>
        </li>
    </ul>
</header>

templates/index.html
{% extends "master.html" %}

{% block title %}
Homepage
{% endblock %}


{% block content %}
<h1>Eddie's Language App</h1>

<p>Expect some content here soon</p>
{% endblock %}

templates/master.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>

  <link rel="stylesheet" href="{% static 'app.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Edu+AU+VIC+WA+NT+Hand:wght@400..700&family=Roboto+Slab:wght@100..900&display=swap"
    rel="stylesheet">
  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  {% include "header.html" %}

  <main>
    {% block content %}
    {% endblock %}
  </main>

</body>

</html>